table Fact_Rejected_Records

	column batch_id
		dataType: string
		sourceColumn: batch_id
		summarizeBy: none

	column reject_type
		dataType: string
		sourceColumn: reject_type
		summarizeBy: none

	column reject_reason
		dataType: string
		sourceColumn: reject_reason
		summarizeBy: none

	column trip_id
		dataType: string
		sourceColumn: trip_id
		summarizeBy: none

	column trip_date
		dataType: dateTime
		sourceColumn: trip_date
		summarizeBy: none

	column trip_total_usd
		dataType: decimal
		sourceColumn: trip_total_usd
		summarizeBy: none

	column trip_miles
		dataType: double
		sourceColumn: trip_miles
		summarizeBy: none

	column duration_seconds
		dataType: double
		sourceColumn: duration_seconds
		summarizeBy: none

	column pickup_community_area
		dataType: int64
		sourceColumn: pickup_community_area
		summarizeBy: none

	measure 'Quarantined rows' = COUNTROWS(Fact_Rejected_Records)
		formatString: #,0

	measure 'Invalid rows detail' = CALCULATE(COUNTROWS(Fact_Rejected_Records),Fact_Rejected_Records[reject_type] = "invalid")
		formatString: #,0

	measure 'Duplicate rows detail' = CALCULATE(COUNTROWS(Fact_Rejected_Records),Fact_Rejected_Records[reject_type] = "duplicate")
		formatString: #,0

	partition Fact_Rejected_Records = m
		mode: import
		source = Table.TransformColumnTypes(#table({"batch_id", "reject_type", "reject_reason", "trip_id", "trip_date", "trip_total_usd", "trip_miles", "duration_seconds", "pickup_community_area"}, {{"DEMO_NOT_A_REAL_RUN", "invalid", "missing_trip_id", null, #date(2023,1,1), 10.25, 2.5, 800, 8}, {"DEMO_NOT_A_REAL_RUN", "invalid", "invalid_trip_total", "demo-trip-02", #date(2023,1,2), -5, 1.2, 500, 32}, {"DEMO_NOT_A_REAL_RUN", "duplicate", "duplicate_trip_id", "demo-trip-03", #date(2023,1,3), 15, 3.2, 900, 8}}), {{"batch_id", type text}, {"reject_type", type text}, {"reject_reason", type text}, {"trip_id", type text}, {"trip_date", type date}, {"trip_total_usd", Currency.Type}, {"trip_miles", type number}, {"duration_seconds", type number}, {"pickup_community_area", Int64.Type}})
