table Fact_Top_Zones

	column rank
		dataType: int64
		sourceColumn: rank
		summarizeBy: none

	column pickup_zone
		dataType: string
		sourceColumn: pickup_zone
		summarizeBy: none

	column trip_count
		dataType: int64
		sourceColumn: trip_count
		summarizeBy: none

	column total_revenue_usd
		dataType: decimal
		sourceColumn: total_revenue_usd
		summarizeBy: none

	measure 'Courses Top 10' = SUM(Fact_Top_Zones[trip_count])
		formatString: #,0

	measure 'Revenu Top 10 USD' = SUM(Fact_Top_Zones[total_revenue_usd])
		formatString: $#,0

	measure 'Part courses Top 10 batch' = DIVIDE([Courses Top 10], CALCULATE([Nb courses], REMOVEFILTERS(DimDate)))
		formatString: 0.0%

	partition Fact_Top_Zones = m
		mode: import
		source = Table.TransformColumnTypes(#table({"rank", "pickup_zone", "trip_count", "total_revenue_usd"}, {{1, "8", 19200, 268224.0}, {2, "32", 16600, 239704.0}, {3, "28", 13700, 204267.0}, {4, "76", 12000, 184560.0}, {5, "24", 10100, 160085.0}, {6, "6", 8800, 143616.0}, {7, "7", 7300, 122567.0}, {8, "33", 6900, 119094.0}, {9, "3", 5800, 102834.0}, {10, "22", 4700, 85540.0}}), {{"rank", Int64.Type}, {"pickup_zone", type text}, {"trip_count", Int64.Type}, {"total_revenue_usd", Currency.Type}})
