table Fact_Quality_Reasons

	column batch_id
		dataType: string
		sourceColumn: batch_id
		summarizeBy: none

	column reject_reason
		dataType: string
		sourceColumn: reject_reason
		summarizeBy: none

	column reject_count
		dataType: int64
		sourceColumn: reject_count
		summarizeBy: none

	measure 'Exceptions by reason' = SUM(Fact_Quality_Reasons[reject_count])
		formatString: #,0

	partition Fact_Quality_Reasons = m
		mode: import
		source = Table.TransformColumnTypes(#table({"batch_id", "reject_reason", "reject_count"}, {{"DEMO_NOT_A_REAL_RUN", "missing_trip_id", 300}, {"DEMO_NOT_A_REAL_RUN", "invalid_trip_total", 200}, {"DEMO_NOT_A_REAL_RUN", "invalid_duration", 160}, {"DEMO_NOT_A_REAL_RUN", "invalid_start_timestamp", 70}, {"DEMO_NOT_A_REAL_RUN", "negative_trip_miles", 20}, {"DEMO_NOT_A_REAL_RUN", "duplicate_trip_id", 300}}), {{"batch_id", type text}, {"reject_reason", type text}, {"reject_count", Int64.Type}})
