table Fact_Daily_Metrics

	column trip_date
		dataType: dateTime
		sourceColumn: trip_date
		summarizeBy: none

	column trip_count
		dataType: int64
		sourceColumn: trip_count
		summarizeBy: none

	column avg_duration_min
		dataType: double
		sourceColumn: avg_duration_min
		summarizeBy: none

	column avg_trip_miles
		dataType: double
		sourceColumn: avg_trip_miles
		summarizeBy: none

	measure 'Durée moyenne pondérée min' = DIVIDE(SUMX(Fact_Daily_Metrics, Fact_Daily_Metrics[trip_count] * Fact_Daily_Metrics[avg_duration_min]), SUM(Fact_Daily_Metrics[trip_count]))
		formatString: 0.0

	measure 'Distance moyenne pondérée miles' = DIVIDE(SUMX(Fact_Daily_Metrics, Fact_Daily_Metrics[trip_count] * Fact_Daily_Metrics[avg_trip_miles]), SUM(Fact_Daily_Metrics[trip_count]))
		formatString: 0.00

	partition Fact_Daily_Metrics = m
		mode: import
		source = Table.TransformColumnTypes(#table({"trip_date", "trip_count", "avg_duration_min", "avg_trip_miles"}, {{#date(2023,1,1), 12500, 12.2, 3.4}, {#date(2023,1,2), 16800, 11.5, 3.8}, {#date(2023,1,3), 14700, 13.1, 3.6}, {#date(2023,1,4), 18000, 12.5, 3.45}, {#date(2023,1,5), 20400, 12.8, 3.9}, {#date(2023,1,6), 22700, 13.4, 4.1}, {#date(2023,1,7), 24700, 14.0, 4.2}}), {{"trip_date", type date}, {"trip_count", Int64.Type}, {"avg_duration_min", type number}, {"avg_trip_miles", type number}})
