table Fact_Daily_Revenue

	column trip_date
		dataType: dateTime
		sourceColumn: trip_date
		summarizeBy: none

	column trip_count
		dataType: int64
		sourceColumn: trip_count
		summarizeBy: none

	column total_revenue_usd
		dataType: decimal
		sourceColumn: total_revenue_usd
		summarizeBy: none

	measure 'Nb courses' = SUM(Fact_Daily_Revenue[trip_count])
		formatString: #,0

	measure 'Montant déclaré USD' = SUM(Fact_Daily_Revenue[total_revenue_usd])
		formatString: $#,0

	measure 'USD par course' = DIVIDE([Montant déclaré USD], [Nb courses])
		formatString: $#,0.00

	measure 'Jours observés' = DISTINCTCOUNT(Fact_Daily_Revenue[trip_date])
		formatString: 0

	partition Fact_Daily_Revenue = m
		mode: import
		source = Table.TransformColumnTypes(#table({"trip_date", "trip_count", "total_revenue_usd"}, {{#date(2023,1,1), 12500, 210300.25}, {#date(2023,1,2), 16800, 281200.5}, {#date(2023,1,3), 14700, 248900.8}, {#date(2023,1,4), 18000, 309000.1}, {#date(2023,1,5), 20400, 358000.2}, {#date(2023,1,6), 22700, 394100.75}, {#date(2023,1,7), 24700, 429500.3}}), {{"trip_date", type date}, {"trip_count", Int64.Type}, {"total_revenue_usd", Currency.Type}})
