table Fact_Quality_Batch

	column batch_id
		dataType: string
		sourceColumn: batch_id
		summarizeBy: none

	column recorded_at_utc
		dataType: string
		sourceColumn: recorded_at_utc
		summarizeBy: none

	column checked_at_utc
		dataType: string
		sourceColumn: checked_at_utc
		summarizeBy: none

	column gate_status
		dataType: string
		sourceColumn: gate_status
		summarizeBy: none

	column raw_rows
		dataType: int64
		sourceColumn: raw_rows
		summarizeBy: none

	column clean_rows
		dataType: int64
		sourceColumn: clean_rows
		summarizeBy: none

	column rejected_rows
		dataType: int64
		sourceColumn: rejected_rows
		summarizeBy: none

	column duplicate_valid_rows
		dataType: int64
		sourceColumn: duplicate_valid_rows
		summarizeBy: none

	column reconciliation_delta
		dataType: int64
		sourceColumn: reconciliation_delta
		summarizeBy: none

	column gold_daily_rows
		dataType: int64
		sourceColumn: gold_daily_rows
		summarizeBy: none

	column gold_top_zones_rows
		dataType: int64
		sourceColumn: gold_top_zones_rows
		summarizeBy: none

	measure 'Raw records' = SUM(Fact_Quality_Batch[raw_rows])
		formatString: #,0

	measure 'Clean records' = SUM(Fact_Quality_Batch[clean_rows])
		formatString: #,0

	measure 'Rejected records' = SUM(Fact_Quality_Batch[rejected_rows])
		formatString: #,0

	measure 'Duplicate records' = SUM(Fact_Quality_Batch[duplicate_valid_rows])
		formatString: #,0

	measure 'Reject rate' = DIVIDE([Rejected records], [Raw records])
		formatString: 0.00%

	measure 'Clean yield' = DIVIDE([Clean records], [Raw records])
		formatString: 0.00%

	measure 'Reconciliation delta' = SUM(Fact_Quality_Batch[reconciliation_delta])
		formatString: #,0

	measure 'Quality gate status' = SELECTEDVALUE(Fact_Quality_Batch[gate_status], "MULTIPLE BATCHES")

	partition Fact_Quality_Batch = m
		mode: import
		source = Table.TransformColumnTypes(#table({"batch_id", "recorded_at_utc", "checked_at_utc", "gate_status", "raw_rows", "clean_rows", "rejected_rows", "duplicate_valid_rows", "reconciliation_delta", "gold_daily_rows", "gold_top_zones_rows"}, {{"DEMO_NOT_A_REAL_RUN", "DEMO_TIMESTAMP", "DEMO_TIMESTAMP", "PASS", 150000, 148950, 750, 300, 0, 7, 10}}), {{"batch_id", type text}, {"recorded_at_utc", type text}, {"checked_at_utc", type text}, {"gate_status", type text}, {"raw_rows", Int64.Type}, {"clean_rows", Int64.Type}, {"rejected_rows", Int64.Type}, {"duplicate_valid_rows", Int64.Type}, {"reconciliation_delta", Int64.Type}, {"gold_daily_rows", Int64.Type}, {"gold_top_zones_rows", Int64.Type}})
